# Put PIVOTAL_API_ACCOUNT_ID and PIVOTAL_API_PROJECT_ID in quotes as they are numbers
PIVOTAL_API_URL:        https://www.pivotaltracker.com/services/v5
PIVOTAL_API_TOKEN:      your_pivotal_tracker_token
PIVOTAL_API_ACCOUNT_ID: your_pivotal_tracker_account_id
PIVOTAL_API_PROJECT_ID: your_pivotal_tracker_project_id
PEOPLE_IMAGES_DIR_URL:  your_team_member_images_directory_url